version: "3.7"

networks:
  ploch-network:
  
services:
  ploch-sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1533"
    environment:
        SA_PASSWORD: "P@ssw0rd"
        ACCEPT_EULA: "Y"
    networks:
      - ploch-network
