<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Ploch.Data.EFCore" />
    <PackageReference Include="Ploch.Data.GenericRepository.EFCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Ploch.Data.SampleApp.Domain.csproj" />
  </ItemGroup>
</Project>
